#version 450

layout(local_size_x = 16, local_size_y = 16) in;
layout(binding = 0, rg16f) uniform readonly image2D inImg;
layout(binding = 1, rg16f) uniform writeonly image2D outImg;

void main() {	
	vec2 res = imageLoad(inImg, ivec2(gl_GlobalInvocationID.xy)).rg;

	res *= 1.0 - 2.0 * ((gl_GlobalInvocationID.x + gl_GlobalInvocationID.y) % 2);
	uint N = gl_WorkGroupSize.x * gl_NumWorkGroups.x; 
	res /= N * N;

	imageStore(outImg, ivec2(gl_GlobalInvocationID.xy), vec4(res, 0, 0));
}
